### ISSUE TITLE
Needs a rubocop engine upgrade

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chefstyle#29]
- rubocop 0.41.1 failed miserably since `rubocop` and `rubocop -a` disagreed about which cops were failing and autofixing didn't fix the right stuff at all.

- rubocop 0.41.2 failed due to infinite looping:

```
930 files inspected, 35 offenses detected, 35 offenses corrected
Infinite loop detected in /Users/lamont/oc/chef4/spec/functional/resource/dsc_script_spec.rb.
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:202:in `check_for_infinite_loop'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:173:in `block in do_inspection_loop'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:172:in `loop'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:172:in `do_inspection_loop'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:87:in `process_file'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:57:in `each'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/runner.rb:35:in `run'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/lib/rubocop/cli.rb:28:in `run'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/bin/rubocop:14:in `block in <top (required)>'
/Users/lamont/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/rubocop-0.41.2/bin/rubocop:13:in `<top (required)>'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/chefstyle-0.4.0/bin/chefstyle:13:in `load'
/Users/lamont/.rvm/gems/ruby-2.2.5/gems/chefstyle-0.4.0/bin/chefstyle:13:in `<top (required)>'
/Users/lamont/.rvm/gems/ruby-2.2.5/bin/chefstyle:22:in `load'
/Users/lamont/.rvm/gems/ruby-2.2.5/bin/chefstyle:22:in `<main>'
```

**Comment by lamont-granquist** [comment]
0.42.0 looks better -- although the infinite looping in that dsc_script_spec.rb file is still there, but its entirely due to some fairly whack use of heredocs inside of let blocks

**Comment by lamont-granquist** [comment]
the infinite loop is most likely just due to badly written code we should fix.  vanilla rubocop autofixes those heredocs via:

```ruby
Inspecting 1 file
W

Offenses:

infinite.rb:1:3: C: [Corrected] Style/InitialIndentation: Indentation of first line in file detected.
  let(:dsc_user_config_data) { <<-EOH
  ^^^
infinite.rb:1:30: C: [Corrected] Style/BlockDelimiters: Avoid using {...} for multi-line blocks.
  let(:dsc_user_config_data) { <<-EOH
                             ^
infinite.rb:1:30: C: [Corrected] Style/TrailingWhitespace: Trailing whitespace detected.
let(:dsc_user_config_data) do
                             ^
infinite.rb:1:32: C: [Corrected] Style/MultilineBlockLayout: Block body expression is on the same line as the block start.
  let(:dsc_user_config_data) { <<-EOH
                               ^^^^^^
infinite.rb:2:1: C: [Corrected] Style/IndentationWidth: Use 2 (not 4) spaces for indentation.
    <<-EOH
^^^^
infinite.rb:13:3: W: [Corrected] Lint/BlockAlignment: end at 13, 2 is not aligned with let(:dsc_user_config_data) do  at 1, 0.
  end
  ^^^

1 file inspected, 6 offenses detected, 6 offenses corrected
```

which results in this code:

```ruby
let(:dsc_user_config_data) do
  <<-EOH
@{
    AllNodes = @(
        @{
            NodeName = "localhost";
            PSDscAllowPlainTextPassword = $true
        }
    )
}

EOH
end
```

**Comment by lamont-granquist** [comment]
we should consider enabling:

* Style/BlockDelimiters
* Style/MultilineBlockLayout

which will most likely eliminate the infinite loop?
